#-*- coding: UTF-8 -*-
from enum import Enum
import pygame
from pygame.locals import *

class DiceImage(Enum):
    DiceBox  = pygame.image.load( r"panel\DiceBox.png" )
    DiceUsed = pygame.image.load( r"panel\DiceUsed.png" )

    DiceNor  = pygame.image.load( r"panel\DiceNor.png" )
    DiceNor2 = pygame.image.load( r"panel\DiceNor2.png" )
    DiceNor3 = pygame.image.load( r"panel\DiceNor3.png" )
    DiceAtk  = pygame.image.load( r"panel\DiceAtk.png" )
    DiceAtk2 = pygame.image.load( r"panel\DiceAtk2.png" )
    DiceAtk3 = pygame.image.load( r"panel\DiceAtk3.png" )
    DiceDef  = pygame.image.load( r"panel\DiceDef.png" )
    DiceDef2 = pygame.image.load( r"panel\DiceDef2.png" )
    DiceDef3 = pygame.image.load( r"panel\DiceDef3.png" )
    DiceMov  = pygame.image.load( r"panel\DiceMov.png" )
    DiceMov2 = pygame.image.load( r"panel\DiceMov2.png" )
    DiceMov3 = pygame.image.load( r"panel\DiceMov3.png" )
    DiceSpc  = pygame.image.load( r"panel\DiceSpc.png" )
    DiceSpc2 = pygame.image.load( r"panel\DiceSpc2.png" )
    DiceSpc3 = pygame.image.load( r"panel\DiceSpc3.png" )
    DiceHeal  = pygame.image.load( r"panel\DiceHeal.png" )
    DiceHeal2 = pygame.image.load( r"panel\DiceHeal2.png" )
    DiceHeal3 = pygame.image.load( r"panel\DiceHeal3.png" )

class AttrImage(Enum):
    Nor = pygame.image.load( r"panel\\AttrNor.png" )
    Atk = pygame.image.load( r"panel\\AttrAtk.png" )
    Def = pygame.image.load( r"panel\\AttrDef.png" )
    Mov = pygame.image.load( r"panel\\AttrMov.png" )
    Spc = pygame.image.load( r"panel\\AttrSpc.png" )
    Heal = pygame.image.load( r"panel\\AttrHeal.png" )

    NorNor1 = pygame.image.load( r"panel\NorBaseNor1.png" )
    NorNor2 = pygame.image.load( r"panel\NorBaseNor2.png" )
    NorNor3 = pygame.image.load( r"panel\NorBaseNor3.png" )
    NorAtk1 = pygame.image.load( r"panel\NorBaseAtk1.png" )
    NorAtk2 = pygame.image.load( r"panel\NorBaseAtk2.png" )
    NorAtk3 = pygame.image.load( r"panel\NorBaseAtk3.png" )
    NorDef1 = pygame.image.load( r"panel\NorBaseDef1.png" )
    NorDef2 = pygame.image.load( r"panel\NorBaseDef2.png" )
    NorDef3 = pygame.image.load( r"panel\NorBaseDef3.png" )
    NorMov1 = pygame.image.load( r"panel\NorBaseMov1.png" )
    NorMov2 = pygame.image.load( r"panel\NorBaseMov2.png" )
    NorMov3 = pygame.image.load( r"panel\NorBaseMov3.png" )
    NorSpc1 = pygame.image.load( r"panel\NorBaseSpc1.png" )
    NorSpc2 = pygame.image.load( r"panel\NorBaseSpc2.png" )
    NorSpc3 = pygame.image.load( r"panel\NorBaseSpc3.png" )
    NorHeal1 = pygame.image.load( r"panel\NorBaseHeal1.png" )
    NorHeal2 = pygame.image.load( r"panel\NorBaseHeal2.png" )
    NorHeal3 = pygame.image.load( r"panel\NorBaseHeal3.png" )

class TowerImage(Enum):    
    TowerBase = pygame.image.load( r"panel\TowerBase.png" )    
    TowerNor1 = pygame.image.load( r"panel\TowerNor1.png" )
    TowerNor2 = pygame.image.load( r"panel\TowerNor2.png" )
    TowerNor3 = pygame.image.load( r"panel\TowerNor3.png" )
    TowerNor4 = pygame.image.load( r"panel\TowerNor4.png" )    
    TowerAtk1 = pygame.image.load( r"panel\TowerAtk1.png" )
    TowerAtk2 = pygame.image.load( r"panel\TowerAtk2.png" )
    TowerAtk3 = pygame.image.load( r"panel\TowerAtk3.png" )
    TowerAtk4 = pygame.image.load( r"panel\TowerAtk4.png" )
    TowerDef1 = pygame.image.load( r"panel\TowerDef1.png" )
    TowerDef2 = pygame.image.load( r"panel\TowerDef2.png" )
    TowerDef3 = pygame.image.load( r"panel\TowerDef3.png" )
    TowerDef4 = pygame.image.load( r"panel\TowerDef4.png" )
    TowerMov1 = pygame.image.load( r"panel\TowerMov1.png" )
    TowerMov2 = pygame.image.load( r"panel\TowerMov2.png" )
    TowerMov3 = pygame.image.load( r"panel\TowerMov3.png" )
    TowerMov4 = pygame.image.load( r"panel\TowerMov4.png" )
    TowerSpc1 = pygame.image.load( r"panel\TowerSpc1.png" )
    TowerSpc2 = pygame.image.load( r"panel\TowerSpc2.png" )
    TowerSpc3 = pygame.image.load( r"panel\TowerSpc3.png" )
    TowerSpc4 = pygame.image.load( r"panel\TowerSpc4.png" )
    TowerHeal1 = pygame.image.load( r"panel\TowerHeal1.png" )
    TowerHeal2 = pygame.image.load( r"panel\TowerHeal2.png" )
    TowerHeal3 = pygame.image.load( r"panel\TowerHeal3.png" )
    TowerHeal4 = pygame.image.load( r"panel\TowerHeal4.png" )    

    NorTower = pygame.image.load( r"panel\NorTower.png" )
    AtkTower = pygame.image.load( r"panel\\AtkTower.png" )
    DefTower = pygame.image.load( r"panel\DefTower.png" )
    MovTower = pygame.image.load( r"panel\MovTower.png" )
    SpcTower = pygame.image.load( r"panel\SpcTower.png" )
    HealTower = pygame.image.load( r"panel\HealTower.png" )